@ProductApi_HostAddress = https://localhost:44356

### GET TEST
GET {{ProductApi_HostAddress}}/weatherforecast
Accept: application/json

###

### LOGIN
POST {{ProductApi_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "1234"
}

###

### GET PROTECTED
GET {{ProductApi_HostAddress}}/api/Product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzc3NTkwMTk2LCJpc3MiOiJQcm9kdWN0QXBpIiwiYXVkIjoiUHJvZHVjdEFwaVVzZXJzIn0.W0EUIxcGydPh-y3E_31XGMt6HlXxMF9O0BL1qEZHl04

###

POST {{ProductApi_HostAddress}}/api/Product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3Nzc1OTQ3MzIsImlzcyI6IlByb2R1Y3RBcGkiLCJhdWQiOiJQcm9kdWN0QXBpVXNlcnMifQ.QYNrTAoAa3jawmJwEWZ87KayZph7doxhL4-qitSj8r0
Content-Type: application/json

{
  "name": "iPad",
  "price": 900
}